vich_uploader:
    db_driver: orm

    mappings:
        photo_profil:
            uri_prefix: '%app.path.photo_profil%'
            upload_destination: '%kernel.project_dir%/public%app.path.photo_profil%'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
